
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
        ACCOUNT_ADD_NEW : "ACCOUNT_ADD_NEW",
        ACCOUNT_EDIT : "ACCOUNT_EDIT",
        CANDIDATE_ADD_NEW : "CANDIDATE_ADD_NEW"
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        ACCOUNT_DELETE : "ACCOUNT_DELETE",
        CANDIDATE_DELETE : "CANDIDATE_DELETE",
        OWNER_DELETE : "OWNER_DELETE"
    },
});
